#!/bin/bash

_nsa() {
	echo "Hey boi, crontab just changed. btw i use gentoo"| mail -s "Debian Sucks, SystemD too." root@localhost.localdomain
}

_watcher() {
	c1=""

	while [[ true ]]
	do
		c2=`md5sum /etc/crontab`
		if [[ $c1 != $c2 ]] ; then
			_nsa
			c1=$c2
		fi
		sleep 10
	done
}

_watcher
