#!/bin/bash
#
# Crontab rules:
# 0 0 * * *
#
# ^ every day at midnight

nsa() {
	echo "Hey boi, crontab just changed. btw i use gentoo"| mail -s "Debian Sucks, SystemD too." root@localhost.localdomain
}

watcher() {
	c1=""

	while [[ true ]]
	do
		c2=`md5sum /etc/crontab`
		if [[ $c1 != $c2 ]] ; then
			nsa
			c1=$c2
		fi
		sleep 10
	done
}

watcher
